linters-settings:
  gocyclo:
    min-complexity: 25
  gofmt:
    simplify: true
  misspell:
    locale: US
  govet:
    disable:
      - shadow
      - nilness
    enable-all: true
  errcheck:
    exclude-functions:
      - (*gorm.io/gorm.DB).AddError

linters:
  enable:
    - gofmt
    - revive
    - gocyclo
    - misspell
    - bodyclose
    - govet
    - unused
    - errcheck
  disable-all: false
  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - .github
  exclude:
    - should have a package comment
    - type name will be used as filter.FilterValidator by other packages, and that stutters; consider calling this Validator
