name: Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"
jobs:
  tests:
    name: Unit and integrations tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20", "1.21"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - if: ${{ matrix.go == '1.21' }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout 5m
